site_name: /Gearpump/

repo_url: http://github.com/intel-hadoop/gearpump

site_description: realtime, streaming

dev_addr: 0.0.0.0:8000

theme_dir: 'custom_theme'

pages:
 - [index.md, Home]
 - [documents/getstarted.md, "User Guide", "Get Started"]
 - [documents/dag_api.md, "User Guide", "DAG API"]
 - [documents/how_to_build.md, "User Guide", "How to Build"]
 - [documents/configuration.md, "User Guide", "Gearpump Configuration"]
 - [documents/run_time_model_description.md, "User Guide", "Runtime Model"]
 - [documents/high_availability_guide.md, "User Guide", "High Availability Guide"]
 - [documents/kafka_tutorial_walk_through.md, "User Guide", "Kafka Source and Sink Example Walk through"]
 - [documents/how_gearpump_do_fail_over.md, "User Guide", "How Gearpump do Fail Over"]
 - [documents/how_to_write_a_streaming_application.md, "User Guide", "How to Write a Streaming Application"]
 - [documents/how_to_write_a_general_distributed_application.md, "User Guide", "How to Write a General Distributed Application"]
 - [documents/serialization_guide.md, "User Guide", "Write your customized serializer"]
 - [documents/intellij_eclipse_development_environment_setup.md, "User Guide", "IDE setup"]
 - [documents/performance.md, "User Guide", "Performance Benchmarks"]
 - [documents/faq.md, "User Guide", "FAQ"]
 - [downloads/downloads.md, "Downloads", "Latest Version"]
 - [downloads/release_notes.html, "Downloads", "Release Notes"]
 - [publications/publications.md, Publications]
 - [usecases/use_cases.md, "Use Cases"]
 - [about/license.md, "About", "License"]
 - [about/acknowledge.md, "About", "Acknowledgement"]
 - [about/contact_us.md, "About", "Contact Us"]