site_name: /Gearpump/

repo_url: http://github.com/intel-hadoop/gearpump

site_description: realtime, streaming

dev_addr: 0.0.0.0:8000

theme_dir: 'custom_theme'

pages:
 - [index.md, Home]
 - [documents/introduction.md, "User Guide", "Introduction"]
 - [documents/getstarted.md, "User Guide", "Get Started"]
 - [documents/concepts.md, "User Guide", "Concepts"]
 - [documents/adminguide.md, "User Guide", "Admin Guide"]
 - [documents/how_to_write_a_streaming_application.md, "User Guide", "Streaming Application Developer Guide"]
 - [documents/how_to_write_a_general_distributed_application.md, "User Guide", "Non-Streaming Application Developer Guide"]
 - [documents/performance.md, "User Guide", "Performance Benchmarks"]
 - [documents/internal.md, "User Guide", "Gearpump Internals"]
 - [documents/examplewalkthrough.md, "User Guide", "Kafka Use case walkthrough"]
 - [documents/commandlinesyntax.md, "User Guide", "Command Line Tools"]
 - [documents/restapi.md, "User Guide", "Rest API Guide"]
 - [documents/configuration_guide.md, "User Guide", "Configuration Guide"]
 - [documents/high_availability_guide.md, "User Guide", "High Availability Guide"]
 - [documents/intellij_eclipse_development_environment_setup.md, "User Guide", "IDE setup"]
 - [documents/faq.md, "User Guide", "FAQ"]
 - [downloads/downloads.md, "Downloads", "Latest Version"]
 - [downloads/release_notes.html, "Downloads", "Release Notes"] 
 - [publications/publications.md, Publications]
 - [usecases/use_cases.md, "Use Cases"]
 - [roadmap.md, "RoadMap"]
 - [about/license.md, "About", "License"]
 - [about/acknowledge.md, "About", "Acknowledgement"]
 - [about/contact_us.md, "About", "Contact Us"]