site_name: /Gearpump/

page_title: Gearpump Stream Processing Engine

repo_url: http://github.com/intel-hadoop/gearpump

site_description: realtime, streaming

dev_addr: 0.0.0.0:8000

theme_dir: 'custom_theme'

pages:
 - [index.md, Home]
 - [0.6/userguide.md, "User Guide", "User Guide"]
 - [0.6/performance.md, "User Guide", "Performance Benchmark"]
 - [downloads.md, Downloads]
 - [publications/publications.md, Publications]
 - [roadmap.md, RoadMap]
 - [about.md, About]