site_name: /Gearpump/

repo_url: http://github.com/intel-hadoop/gearpump

site_description: realtime, streaming

dev_addr: 0.0.0.0:8000

pages:
 - [index.md, Home]
 - [documents/getstarted.md, "User Guide", "Get Started"]
 - [documents/dag_api.md, "User Guide", "DAG API"]
 - [documents/how_to_build.md, "User Guide", "How to Build"]
 - [documents/document.md, "User Guide", "Documents"]
 - [documents/configuration.md, "User Guide", "Gearpump Configuration"]
 - [documents/run_time_model_description.md, "User Guide", "Runtime Model"]
 - [documents/high_availability_guide.md, "User Guide", "High Availability Guide"]
 - [documents/kafka_tutorial_walk_through.md, "User Guide", "Kafka Source and Sink Example Walk through"]
 - [documents/how_gearpump_do_fail_over.md, "User Guide", "How Gearpump do Fail Over"]
 - [documents/how_to_write_a_streaming_application.md, "User Guide", "How to Write a Streaming Application"]
 - [documents/how_to_write_a_general_distributed_application.md, "User Guide", "How to Write a General Distributed Application"]
 - [documents/serialization_guide.md, "User Guide", "Write your customized serializer"]
 - [documents/sbt_and_maven_depandency_setting.md, "User Guide", "sbt and Maven Dependencies settings"]
 - [documents/intellij_eclipse_development_environment_setup.md, "User Guide", "IDE setup"]
 - [documents/performance.md, "User Guide", "Performance Benchmarks"]
 - [documents/faq.md, "User Guide", "FAQ"]
 - [downloads/downloads.md, "Downloads", "Latest Version"]
 - [downloads/releasenotes.md, "Downloads", "Release Notes"]
 - [usecases/use_cases.md, "Use Cases"]
 - [about/license.md, "About", "License"]
 - [about/acknowledge.md, "About", "Acknowledgement"]
 - [about/howto_get_help.md, "About", "Contact Us"]